learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from template_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('template_app/',include('template_app.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/template_app/urls.py
from django.conf.urls import url
from template_app import views
from django.urls import path

app_name='template_app'

urlpatterns=[
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other')
]

learning_templates/template_app/models.py
from django.db import models

# Create your models here.

learning_templates/template_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict={'text':'hello world','number':100}
    return render(request,'template_app/index.html',context_dict)

def other(request):
    return render(request,'template_app/other.html')

def relative(request):
    return render(request,'template_app/relative_url_template.html')

learning_templates/templates/template_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <!-- <ul class="nav navbar-nav">
          <li ><a class="navbar-brand" href="#">BRAND</a></li>
          <li><a class="navbar-link"href="#">Admin</a></li>
          <li><a class="navbar-link" href="#">Other</a></li>
        </ul> -->
        <ul class="nav nav-tabs">
          <li class="nav-item"><a class="nav-link active" href="{% url 'index'%}">BRAND</a></li>
        </ul>
        <ul class="nav nav-tabs">
          <li class="nav-item"><a class="nav-link active" href="{% url 'admin:index'%}">Admin</a></li>
        </ul>
        <ul class="nav nav-tabs">
          <li class="nav-item"><a class="nav-link active" href="{% url 'template_app:other'%}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/template_app/index.html
<!DOCTYPE html>
{% extends "template_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to index</h1>
    <h2>This is index.html from inheritance template</h2>
    {{text|upper}}
    {{text|cut:'hello'}}
    {{number|add:"99"}}
  {% endblock %}

learning_templates/templates/template_app/other.html
<!DOCTYPE html>
{% extends "template_app/base.html"%}
  {% block body_block %}
    <h1>Welcome to other!</h1>
    <h2>This is an example of template inheritance</h2>
    {% endblock %}

learning_templates/templates/template_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>welcome to relative url templates</h1>
    <a href="{% url 'template_app:other' %}">The other page </a>
    <a href="{% url 'admin:index' %}">The admin page</a>
    <a href="{% url 'index' %}">Link to index page</a>
  </body>
</html>